perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_ZA.utf-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
/var/tmp/slurmd.spool/job1912601/slurm_script: line 8: nvcc: command not found
Loading python/miniconda3-py38-usr-A
  Loading requirement: compilers/gcc820 mpi/openmpi-4.0.1
Training AGCRN for horizons:16   split:0
Traceback (most recent call last):
  File "runAGCRN.py", line 18, in <module>
    agcrn_trainer.execute()
  File "/home/gbxade002/WEATHER-FLOW/Execute/agcrnExecute.py", line 51, in execute
    self.prep_split_data(forecast_len, split)
  File "/home/gbxade002/WEATHER-FLOW/Execute/agcrnExecute.py", line 269, in prep_split_data
    self.train_loader, self.val_loader, self.test_loader, self.scaler = agcrnUtil.get_dataloader(predictor_attributes,horizon, k, 
  File "/home/gbxade002/WEATHER-FLOW/Utils/agcrnUtils.py", line 175, in get_dataloader
    data, dataY = load_st_dataset(predictor_attributes, n_stations)        # B, N, D     
  File "/home/gbxade002/WEATHER-FLOW/Utils/agcrnUtils.py", line 249, in load_st_dataset
    data = pd.read_csv('DataNew/Graph Neural Network Data/Graph Station Data/graph.csv')
  File "/home/gbxade002/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/gbxade002/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/gbxade002/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/gbxade002/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/gbxade002/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/gbxade002/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/gbxade002/.local/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/gbxade002/.local/lib/python3.8/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'DataNew/Graph Neural Network Data/Graph Station Data/graph.csv'
